### ISSUE TITLE
simpleEllipse() not working

### ISSUE THREAD

**Issue by Jfgrass** [hredestig/pcaMethods#10]
Hi! I am trying to run _simpleEllipse()_  function to detect outliers in a two principal components score plot using Hotelling T2 but I get the following warning when I run it:

Error in simpleEllipse(PCA_score_frame$PC1, PCA_score_frame$PC2, alfa = 0.95,  : 
  could not find function "simpleEllipse"

The package seems to be well installed 

Thanks in advance

Kind regards

**Comment by hredestig** [comment]
simpleEllipse is not an exported function (there are many other packages that implement this better) but you can still use this version by calling `pcaMethods:::simpleEllipse()`
