### ISSUE TITLE
unable to find an inherited method for function ‘type’ for signature ‘"nniRes"’

### ISSUE THREAD

**Issue by iquasere** [hredestig/pcaMethods#15]
Greetings!

I have tried to use the local least squares imputation for a proteomics dataset. Running ```llsImpute(transposed_data)``` warned me of
```
Warning message:
In llsImpute(transp) :
  Cluster size larger than number of complete genes, using allVariables = TRUE
``` 
but didn't fail. Trying to see the imputed data got me an error though
```
        Variables
        Samples
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘nObs’ for signature ‘"nniRes"’
```
Why is that?

**Comment by hredestig** [comment]
Can you share a reproducible example, like transcript of your R-session, so I can exactly what you did?

**Comment by iquasere** [comment]
Sorry, I hadn't realized you answered. This problem was overcomed, so I'm closing it.
