### ISSUE TITLE
matlab pca "als" 

### ISSUE THREAD

**Issue by lxzdong** [hredestig/pcaMethods#3]
Hi, 

I checked different documents, and found that pcaMethods follows the algorithms of BPCA and PPCA  in Matlab, and provides equivalent functions for them. 

However, anther frequently adopted method in Matlab is the "als" method under the default pca function. So, do we have an equivalent function in pcaMethods for the "als" under the pca function in Matlab? 

Thank you,
Russell

**Comment by hredestig** [comment]
Hi! No, do you have a reference to that algorithm?

**Comment by lxzdong** [comment]
Hi, 

Please use the following link for a quick reference (you can just search for 'als' on that page), and I also paste two screenshots just for your information. 

https://www.mathworks.com/help/stats/pca.html

The "als", alternating least squares, is a bult-in method from Matlab's default pca function. 

Thanks,

![pic1](https://user-images.githubusercontent.com/16121569/41187092-e783e35e-6b70-11e8-86ea-e4f7fdf338d9.png)
![pic2](https://user-images.githubusercontent.com/16121569/41187101-eedbddd2-6b70-11e8-8a10-933a9e98e996.png)

**Comment by hredestig** [comment]
Looks like a nice algorithm but sadly don't have the time to work on that so will close this issue :/
