### ISSUE TITLE
Doesn't seem to work with R 3.5.1

### ISSUE THREAD

**Issue by bharris12** [hredestig/pcaMethods#4]
Installing both with devtools and bioconductor exists and fails. bioconductor claims it will not work with 3.5.1

**Comment by hredestig** [comment]
Ouch, thanks, will have a look.

**Comment by hredestig** [comment]
What platform are  you testing on exactly? bioconductor check reports are [all green](http://bioconductor.org/checkResults/release/bioc-LATEST/pcaMethods/)..

**Comment by hredestig** [comment]
Can't find any obvious issues, installs and checks fine for me with 3.5.1. If you let me know which platform you use, how exactly you try to install the package, I can try to see what the problem may be.

**Comment by bharris12** [comment]
There was an unrelated problem with the server I was downloading it on, all fixed. Sorry For the confusion

**Comment by hredestig** [comment]
Alright, no problem glad it worked out
