### ISSUE TITLE
Support IRLBA method and use it as default for sparse matrices

### ISSUE THREAD

**Issue by flying-sheep** [hredestig/pcaMethods#7]
The [irlba](https://github.com/bwlewis/irlba) package handles sparse matrices (from the Matrix package) without converting them into a dense matrix. This can make the difference between blowing up the memory and just working.

pcaMethods should use the `irlba` method and use it as a default for sparse matrices.

**Comment by hredestig** [comment]
Ouch surely wouldn't want to blow any memory up. Happy to review a pull request if you want send one.

**Comment by flying-sheep** [comment]
Hi! What release/PR is this completed in?

**Comment by hredestig** [comment]
It isn't, sorry, adding irlba is not that straight-forward and I don't have the bandwidth to work on it.

**Comment by flying-sheep** [comment]
I asked because you closed it as completed as opposed to “not planned”:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/291575/214353572-42d35da7-cebc-4406-b767-2cb53c6974de.png">
